const rules = [
  {
    id: 'R01',
    room: 'CR-101',
    category: 'After-hours auto-off',
    description: 'After 18:00 with 10 minutes no motion and door closed → Lights OFF, HVAC ECO.',
    changes: { lights: 'OFF', hvac: 'ECO' },
  },
  {
    id: 'R02',
    room: 'CR-102',
    category: 'After-hours auto-off',
    description: 'After 18:00 with 12 minutes no motion and door closed → Lights OFF, HVAC ECO.',
    changes: { lights: 'OFF', hvac: 'ECO' },
  },
  {
    id: 'R03',
    room: 'CR-103',
    category: 'After-hours auto-off',
    description: 'After 18:00 with 8 minutes no motion and door closed → Lights OFF, HVAC ECO.',
    changes: { lights: 'OFF', hvac: 'ECO' },
  },
  {
    id: 'R04',
    room: 'CR-104',
    category: 'After-hours auto-off',
    description: 'After 18:00 with 10 minutes no motion and door closed → Lights OFF, HVAC ECO.',
    changes: { lights: 'OFF', hvac: 'ECO' },
  },
  {
    id: 'R05',
    room: 'CR-105',
    category: 'After-hours auto-off',
    description: 'After 18:00 with 10 minutes no motion and door closed → Lights OFF, dim to 0 over 30 s, HVAC ECO.',
    changes: { lights: 'OFF', hvac: 'ECO', dimTo: 0, dimDuration: 30 },
  },
  {
    id: 'R06',
    room: 'CR-101',
    category: 'CO₂ ventilation boost',
    description: 'CO₂ >1000 ppm for 5 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R07',
    room: 'CR-102',
    category: 'CO₂ ventilation boost',
    description: 'CO₂ >950 ppm for 5 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R08',
    room: 'CR-103',
    category: 'CO₂ ventilation boost',
    description: 'CO₂ >1100 ppm for 3 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R09',
    room: 'CR-104',
    category: 'CO₂ ventilation boost',
    description: 'CO₂ >1000 ppm for 5 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R10',
    room: 'CR-105',
    category: 'CO₂ ventilation boost',
    description: 'CO₂ >900 ppm for 7 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R11',
    room: 'CR-101',
    category: 'Temperature comfort',
    description: 'Temperature >26 °C for 10 minutes with motion → setpoint decreased by 1 °C (min 22 °C).',
    changes: { setpointDelta: -1, minSetpoint: 22 },
  },
  {
    id: 'R12',
    room: 'CR-102',
    category: 'Temperature comfort',
    description: 'Temperature <20 °C for 10 minutes with motion → setpoint increased by 1 °C (max 24 °C).',
    changes: { setpointDelta: 1, maxSetpoint: 24 },
  },
  {
    id: 'R13',
    room: 'CR-103',
    category: 'Temperature comfort',
    description: 'Temperature >27 °C for 5 minutes with motion → HVAC BOOST.',
    changes: { hvac: 'BOOST' },
  },
  {
    id: 'R14',
    room: 'CR-104',
    category: 'Temperature comfort',
    description: 'Temperature rising >2 °C in 10 minutes with motion → Alert (HVAC check).',
    changes: { alert: 'HVAC check' },
  },
  {
    id: 'R15',
    room: 'CR-105',
    category: 'Temperature comfort',
    description: 'Temperature >25 °C for 15 minutes with CO₂ >1000 ppm → HVAC BOOST + alert “stuffy room”.',
    changes: { hvac: 'BOOST', alert: 'stuffy room' },
  },
];

export default rules;
